In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Sales_dataset (1).csv')

In [5]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,?,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9914,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9915,9797,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9916,9798,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9917,9799,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9918,9800,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

# nulls= city,postal_code,sales

In [6]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City             26
State             0
Postal Code      43
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             2
dtype: int64

# fill the null values of City by mode

In [7]:
df['City']=df['City'].fillna(df['City'].mode()[0])

In [8]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      43
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             2
dtype: int64

# Convert the 'Sales' column to numeric

In [9]:
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

# fill the null of sales by mean

In [10]:
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())

In [11]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      43
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

# dropping column postal code

In [12]:
df.drop(columns=['Postal Code'],inplace=True)

In [13]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9919 entries, 0 to 9918
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9919 non-null   int64
 1   Order ID       9919 non-null   object
 2   Order Date     9919 non-null   object
 3   Ship Date      9919 non-null   object
 4   Ship Mode      9919 non-null   object
 5   Customer ID    9919 non-null   object
 6   Customer Name  9919 non-null   object
 7   Segment        9919 non-null   object
 8   Country        9919 non-null   object
 9   City           9919 non-null   object
 10  State          9919 non-null   object
 11  Region         9919 non-null   object
 12  Product ID     9919 non-null   object
 13  Category       9919 non-null   object
 14  Sub-Category   9919 non-null   object
 15  Product Name   9919 non-null   object
 16  Sales          9919 non-null   float64
dtypes: float64(1), int64(1), object(15)
memory usage: 1.3+ MB

In [15]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9914,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9915,9797,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9916,9798,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9917,9799,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9918,9800,CA-2016-128608,12/1/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

# convert data type of orderdate to date time

In [16]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, errors='coerce')

In [17]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

# convert data type of ship date to date time

In [18]:
df['Ship Date']=pd.to_datetime(df['Ship Date'],dayfirst=True,errors='coerce')

# making a new column "day" of order date

In [19]:
df['Day_of_order']=df['Order Date'].dt.day

# making a new column "month" of order date

In [20]:
df["Month_of_order"]=df['Order Date'].dt.month

# making a new column "Name of day" of order date

In [21]:
df['Day Name']=df['Order Date'].dt.day_name()

# making a new column "month" of order date

In [22]:
df["Month Name"]=df['Order Date'].dt.month_name()

# making a new column "year" of order date

In [23]:
df["Year"]=df['Order Date'].dt.year

# making a new column "deliery delays" of order date

In [24]:
df["Delivery Delay (Dayes)"] = (df["Ship Date"] - df["Order Date"])

In [25]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Day_of_order,Month_of_order,Day Name,Month Name,Year,Delivery Delay (Dayes)
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,8,11,Wednesday,November,2017,3 days
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,8,11,Wednesday,November,2017,3 days
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,12,6,Monday,June,2017,4 days
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,11,10,Tuesday,October,2016,7 days
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,11,10,Tuesday,October,2016,7 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9914,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,...,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980,21,5,Sunday,May,2017,7 days
9915,9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680,12,1,Tuesday,January,2016,5 days
9916,9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Technology,Phones,GE 30524EE4,235.1880,12,1,Tuesday,January,2016,5 days
9917,9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760,12,1,Tuesday,January,2016,5 days
9918,9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,...,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840,12,1,Tuesday,January,2016,5 days

#
replace 2018 by 2025,
replace 2017 by 2024,
replace 2016 by 2023,
replace 2015 by 2022,

In [26]:
df['Year'].unique()

array([2017, 2016, 2015, 2018], dtype=int32)

In [27]:
df['Year']=df['Year'].replace(2018,2025)

In [28]:
df['Year']=df['Year'].replace(2017,2024)

In [29]:
df['Year']=df['Year'].replace(2016,2023)

In [30]:
df['Year']=df['Year'].replace(2015,2022)

In [31]:
df['Year'].head(15)

0     2024
1     2024
2     2024
3     2023
4     2023
5     2022
6     2022
7     2022
8     2022
9     2022
10    2022
11    2022
12    2025
13    2024
14    2023
Name: Year, dtype: int32

In [32]:
df['Year'].tail(15)

9904    2023
9905    2022
9906    2025
9907    2025
9908    2025
9909    2025
9910    2022
9911    2022
9912    2022
9913    2022
9914    2024
9915    2023
9916    2023
9917    2023
9918    2023
Name: Year, dtype: int32

In [33]:
df['Year'].unique()

array([2024, 2023, 2022, 2025], dtype=int32)

In [34]:
df.head(15)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Day_of_order,Month_of_order,Day Name,Month Name,Year,Delivery Delay (Dayes)
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,8,11,Wednesday,November,2024,3 days
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,8,11,Wednesday,November,2024,3 days
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,12,6,Monday,June,2024,4 days
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,11,10,Tuesday,October,2023,7 days
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,11,10,Tuesday,October,2023,7 days
5,6,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,9,6,Tuesday,June,2022,5 days
6,7,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Art,Newell 322,7.2800,9,6,Tuesday,June,2022,5 days
7,8,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,9,6,Tuesday,June,2022,5 days
8,9,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,9,6,Tuesday,June,2022,5 days
9,10,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,9,6,Tuesday,June,2022,5 days
10,11,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,6,Tuesday,June,2022,5 days
11,12,CA-2015-115812,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,9,6,Tuesday,June,2022,5 days
12,13,CA-2018-114412,2018-04-15,2018-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,Office Supplies,Paper,Xerox 1967,15.5520,15,4,Sunday,April,2025,5 days
13,14,CA-2017-161389,2017-12-05,2017-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,5,12,Tuesday,December,2024,5 days
14,15,US-2016-118983,2016-11-22,2016-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,22,11,Tuesday,November,2023,4 days

# Check dublicated

In [ ]:
for column in df.columns:
    if df[column].duplicated().any():
        print(f"Column '{column}' has duplicates.")
    else:
        print(f"Column '{column}' has no duplicates.")

In [62]:
df.duplicated().sum()

119

In [64]:
df.drop_duplicates(inplace=True)

In [65]:
df.duplicated().sum()

0

In [63]:
df.to_csv('project_last.csv')